title = "Org-wide Gitleaks Config"
description = "Centralized ruleset for detecting secrets across all repos"
version = 3

# ==========================
# Global Allowlist
# ==========================
[allowlist]
description = "Global allowlist"
regexes = [
  '''127\.0\.0\.1''',     # ignore localhost
  '''example\.com''',    # ignore example.com
  '''dummysecret''',     # ignore test strings
  '''testpassword''',
]
paths = [
  '''test_data/''',       # ignore test files
  '''docs/''',            # ignore documentation
]

# ==========================
# Rules Section
# ==========================

# Generic API Keys / Secrets
[[rules]]
id = "generic-api-key"
description = "Generic API Key or Secret"
regex = '''(?i)(api[_-]?key|secret|token|password)[\s:=]+[0-9a-zA-Z-_]{8,}'''
tags = ["apikey", "generic", "credentials"]

# AWS Keys
[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["aws", "key"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Key"
regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]'''
tags = ["aws", "secret"]

# Google Cloud API Key
[[rules]]
id = "google-api-key"
description = "Google API Key"
regex = '''AIza[0-9A-Za-z\-_]{35}'''
tags = ["gcp", "apikey"]

# GitHub Personal Access Token
[[rules]]
id = "github-pat"
description = "GitHub Personal Access Token"
regex = '''gh[pousr]_[0-9a-zA-Z]{36}'''
tags = ["github", "token"]

# Slack Token
[[rules]]
id = "slack-token"
description = "Slack Token"
regex = '''xox[baprs]-([0-9a-zA-Z]{10,48})'''
tags = ["slack", "token"]

# Stripe Secret Key
[[rules]]
id = "stripe-secret-key"
description = "Stripe Secret Key"
regex = '''sk_live_[0-9a-zA-Z]{24}'''
tags = ["stripe", "apikey"]

# Twilio API Key
[[rules]]
id = "twilio-api-key"
description = "Twilio API Key"
regex = '''SK[0-9a-fA-F]{32}'''
tags = ["twilio", "apikey"]

# Azure Storage Key
[[rules]]
id = "azure-storage-key"
description = "Azure Storage Account Key"
regex = '''(?i)(?<![a-z0-9])[A-Za-z0-9+\/]{88}(?![a-z0-9])'''
tags = ["azure", "storage", "key"]

# Private Key
[[rules]]
id = "private-key"
description = "Private Key (PEM)"
regex = '''-----BEGIN( RSA)? PRIVATE KEY-----'''
tags = ["key", "private", "pem"]

# JWT Token
[[rules]]
id = "jwt"
description = "JSON Web Token (JWT)"
regex = '''eyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}'''
tags = ["jwt", "token"]

# Dotenv / INI style variables
[[rules]]
id = "dotenv-credentials"
description = "Secrets in .env or .ini files"
regex = '''(?i)(SECRET|TOKEN|PASSWORD|DB_PASS|DB_PASSWORD|DB_USER|API_KEY|ACCESS_KEY|PRIVATE_KEY)[\s:=]+['"]?.{6,}['"]?'''
tags = ["env", "ini", "credentials"]

# SQL Connection Strings
[[rules]]
id = "sql-connection-string"
description = "SQL DB Connection String"
regex = '''(?i)(Server|Data Source|Database|Uid|User Id|PWD|Password)=.{6,}'''
tags = ["sql", "database", "credentials"]
