title = "Gitleaks Custom Ruleset"

# Global allowlist (patterns that should be ignored)
[allowlist]
description = "Global allowlist"
regexes = [
  '''127\.0\.0\.1''',   # ignore localhost
  '''example\.com''',  # ignore example.com
]
paths = [
  '''test_data/''',    # ignore test files
  '''docs/''',         # ignore documentation
]

# Rules
[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key|secret|token|password)[\s:=]+[0-9a-zA-Z-_]{16,}'''
tags = ["apikey", "generic"]

[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["aws", "key"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Key"
regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]'''
tags = ["aws", "secret"]

[[rules]]
id = "github-pat"
description = "GitHub Personal Access Token"
regex = '''ghp_[0-9a-zA-Z]{36}'''
tags = ["github", "token"]

[[rules]]
id = "slack-token"
description = "Slack Token"
regex = '''xox[baprs]-([0-9a-zA-Z]{10,48})'''
tags = ["slack", "token"]

[[rules]]
id = "google-api-key"
description = "Google API Key"
regex = '''AIza[0-9A-Za-z\\-_]{35}'''
tags = ["gcp", "apikey"]
