title = "Custom AWS Secret Rules"

# AWS Access Key (covers AKIA and ALIA style)
[[rules]]
id = "AWS_ACCESS_KEY"
description = "AWS Access Key"
regex = '''(A3T|AKIA|ALIA|ACCA|ASIA)[0-9A-Z]{16}'''
tags = ["key", "AWS"]

# AWS Secret Key (allows = or : and 40–45 chars)
[[rules]]
id = "AWS_SECRET_KEY"
description = "AWS Secret Access Key"
regex = '''(?i)aws[_-]?secret[_-]?access[_-]?key.?[:=]\s*([A-Za-z0-9/+=]{40,45})'''
tags = ["key", "AWS"]
